export const SET_NEWS = 'SET_NEWS';
export const SET_STAFF = 'SET_STAFF';
export const SET_STAFF_DETAIL = 'SET_STAFF_DETAIL';
export const BEGIN_DATA_REQUEST = 'BEGIN_DATA_REQUEST';
export const SUCCESS_DATA_REQUEST = 'SUCCESS_DATA_REQUEST';
export const FAIL_DATA_REQUEST = ' FAIL_DATA_REQUEST';
export const SET_BANNER = 'SET_BANNER';
