export default {
  CLICK_HAMBURGERMENU: 'CLICK_HAMBURGERMENU',
  CLICK_HAMBURGERTITLE: 'CLICK_HAMBURGERTITLE',
  CLICK_HAMBURGERLINK: 'CLICK_HAMBURGERLINK',
  SET_PAGENUMBERSTATE: 'SET_PAGENUMBERSTATE',
  CLICK_PAGENUMBER: 'CLICK_PAGENUMBER',
  CLICK_PAGECHEVRON: 'CLICK_PAGECHEVRON',
  SET_PAGE_CONTENT: 'SET_PAGE_CONTENT',
  SET_NAVBAR_ACTIVEITEM: 'SET_NAVBAR_ACTIVEITEM',
};
