export default {
  CLICK_HAMBURGER_MENU: 'CLICK_HAMBURGER_MENU',
  CLICK_HAMBURGER_TITLE: 'CLICK_HAMBURGER_TITLE',
  CLICK_HAMBURGER_LINK: 'CLICK_HAMBURGER_LINK',
  SET_PAGENUMBER_STATE: 'SET_PAGENUMBER_STATE',
  CLICK_PAGENUMBER: 'CLICK_PAGENUMBER',
  SET_NEWSLOAD_STATE: 'SET_NEWSLOAD_STATE',
  SET_PAGE_CONTENT: 'SET_PAGE_CONTENT',
  SET_NAVBAR_ACTIVEITEM: 'SET_NAVBAR_ACTIVEITEM',
};
