export default {
  CLICK_HAMBURGERMENU: 'CLICK_HAMBURGERMENU',
  CLICK_HAMBURGERTITLE_1: 'CLICK_HAMBURGERTITLE_1',
  CLICK_HAMBURGERTITLE_2: 'CLICK_HAMBURGERTITLE_2',
  CLICK_HAMBURGERTITLE_3: 'CLICK_HAMBURGERTITLE_3',
  CLICK_HAMBURGERTITLE_4: 'CLICK_HAMBURGERTITLE_4',
  CLICK_HAMBURGERTITLE_5: 'CLICK_HAMBURGERTITLE_5',
  CLICK_HAMBURGERLINK: 'CLICK_HAMBURGERLINK',
};
